---
- name: Check php
  stat:
    path: "{{ php_dir }}/{{ php_version }}"
  register: specific_version_php

- name: Write build default configuration
  lineinfile:
    path: "{{ php_phpbuild_root }}/share/php-build/default_configure_options"
    line: '--with-freetype-dir'

- name: Write build configuration for php7.x
  lineinfile:
    path: "{{ php_phpbuild_root }}/share/php-build/definitions/{{ php_version }}"
    line: 'configure_option "--with-libzip"'

- name: Build php "{{ php_version }}"
  command: "{{ php_phpbuild_root }}/bin/php-build {{ php_version }} {{ php_dir }}/{{ php_version }}"
  environment:
    PHP_BUILD_EXTRA_MAKE_ARGUMENTS: "{{ php_PHP_BUILD_EXTRA_MAKE_ARGUMENTS }}"
  when: not specific_version_php.stat.exists

- name: Set configurations
  lineinfile:
    path: "{{ php_dir }}/{{ php_version }}/etc/php.ini"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items: "{{ php_configurations }}"

- name: Configuration for php-fpm.conf
  template:
    src: php-fpm.conf.j2
    dest: "{{ php_dir }}/{{ php_version }}/etc/php-fpm.conf"
    owner: root
    group: root
    mode: 0644

- name: Delete www.conf,www.conf.default
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ php_dir }}/{{ php_version }}/etc/php-fpm.d/www.conf"
    - "{{ php_dir }}/{{ php_version }}/etc/php-fpm.d/www.conf.default"
    - "{{ php_dir }}/{{ php_version }}/etc/php-fpm.conf.default"

- name: Create directory
  file:
    path: "{{ php_dir }}/{{ php_version }}/etc/php-fpm.d/"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create default php-fpm pool configuration
  template:
    src: pool.conf.j2
    dest: "{{ php_dir }}/{{ php_version }}/etc/php-fpm.d/{{ php_fpm_pool.pool }}.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart_phpfpm

- name: Create systemd unit service file
  template:
    src: phpfpm-version.service.j2
    dest: "/etc/systemd/system/phpfpm-{{ php_version }}.service"
    owner: root
    group: root
    mode: 0644
  notify: restart_phpfpm

- name: Start service
  systemd:
    name: "phpfpm-{{ php_version }}.service"
    daemon_reload: yes
    enabled: yes
    state: started
